name: mobile_sim_shop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  logger: ^2.5.0

  #screen splash
  flutter_native_splash: ^2.4.4

  #icons
  cupertino_icons: ^1.0.8

  #fonts
  google_fonts: ^6.2.1

  flutter_screenutil: ^5.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/vectors/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
            - asset: assets/fonts/Montserrat-Black.ttf
              weight: 800
            - asset: assets/fonts/Montserrat-Bold.ttf
              weight: 700
            - asset: assets/fonts/Montserrat-Medium.ttf
              weight: 500
            - asset: assets/fonts/Montserrat-Regular.ttf
              weight: 400


