name: mobile_sim_shop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  logger: ^2.5.0
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  carousel_slider: ^5.0.0
  awesome_snackbar_content: ^0.1.5
  #screen splash
  flutter_native_splash: ^2.4.4
  go_router: ^14.8.1
  readmore: ^3.0.0
  #firebase
  firebase_core: ^3.11.0
  dartz: ^0.10.1
  get_it: ^8.0.3
  firebase_auth: ^5.4.2
  snapshot: ^0.2.6+1
  cloud_firestore: ^5.6.3
  connectivity_plus: ^6.1.3
  lottie: ^2.7.0
  google_sign_in: ^5.3.0
  #icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.10  # Thêm để mở URL đăng nhập
  webview_flutter: ^4.4.2
  uuid: ^4.5.1
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.8
  http: ^1.2.0
  rxdart: ^0.27.2
  #fonts
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.0
  geolocator: ^10.0.0
  geocoding: ^2.1.0
  #local source
  shared_preferences: ^2.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/animations/
    - assets/icons/categories/
  fonts:
    - family: Montserrat
      fonts:
            - asset: assets/fonts/Montserrat-Black.ttf
              weight: 800
            - asset: assets/fonts/Montserrat-Bold.ttf
              weight: 700
            - asset: assets/fonts/Montserrat-Medium.ttf
              weight: 500
            - asset: assets/fonts/Montserrat-Regular.ttf
              weight: 400


